<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Cerneala.UI.Detective" />
    <Using Include="Cerneala.Drawing.Prism.Execution" />
    <Using Include="Cerneala.Drawing.Prism.Kernels" />
    <Using Include="Cerneala.Drawing.Prism.Surfaces" />
    <Using Include="Cerneala.UI.Hosting.Windowing" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cerneala.csproj" />
    <ProjectReference Include="..\..\Cerneala.Backends.MonoGame\Cerneala.Backends.MonoGame.csproj" />
    <ProjectReference Include="..\..\Cerneala.Backends.SdlGpu\Cerneala.Backends.SdlGpu.csproj" />
    <ProjectReference Include="..\..\Cerneala.Platforms.Sdl3\Cerneala.Platforms.Sdl3.csproj" />
    <ProjectReference Include="..\..\Cerneala.Platforms.Win32\Cerneala.Platforms.Win32.csproj" />
    <ProjectReference Include="..\..\CernealaPresentation\CernealaPresentation.csproj" />
    <ProjectReference Include="..\..\Playground\Cerneala.Playground\Cerneala.Playground.csproj" />
    <ProjectReference Include="..\Cerneala.WindowsDxSmoke\Cerneala.WindowsDxSmoke.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
