param(
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = [IO.Path]::GetFullPath(
    [IO.Path]::Combine($PSScriptRoot, '..', '..'))
$catalogPath = [IO.Path]::Combine(
    $repositoryRoot,
    'Cerneala.SourceGen',
    'Prism',
    'Catalog',
    'prism-catalog.json')
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = [IO.Path]::Combine(
        $repositoryRoot,
        'docs',
        'prism-filter-reference.generated.md')
}
elseif (-not [IO.Path]::IsPathRooted($OutputPath)) {
    $OutputPath = [IO.Path]::GetFullPath(
        [IO.Path]::Combine($repositoryRoot, $OutputPath))
}

$catalogBytes = [IO.File]::ReadAllBytes($catalogPath)
$catalogHash = [Convert]::ToHexString(
    [Security.Cryptography.SHA256]::HashData($catalogBytes)
).ToLowerInvariant()
$catalog = [Text.Encoding]::UTF8.GetString($catalogBytes) |
    ConvertFrom-Json
$filters = @(
    $catalog.entries |
        Where-Object { $_.kind -eq 'filter' } |
        Sort-Object stableId
)
$profiles = @{}
foreach ($profile in $catalog.executionProfiles) {
    $profiles[$profile.category] = $profile
}

function Format-Scalar {
    param([object]$Value)

    if ($null -eq $Value) {
        return 'null'
    }
    if ($Value -is [bool]) {
        return $Value.ToString().ToLowerInvariant()
    }
    if ($Value -is [Array]) {
        return ($Value | ForEach-Object {
            Format-Scalar -Value $_
        }) -join ','
    }
    if ($Value -is [string]) {
        return $Value.Replace('|', '\|').Replace('`', '\`')
    }
    return [Convert]::ToString(
        $Value,
        [Globalization.CultureInfo]::InvariantCulture)
}

function Format-Domain {
    param([object]$Domain)

    $minimum = if ($null -eq $Domain.minimum) {
        ''
    }
    else {
        Format-Scalar -Value $Domain.minimum
    }
    $maximum = if ($null -eq $Domain.maximum) {
        ''
    }
    else {
        Format-Scalar -Value $Domain.maximum
    }
    if ([string]::IsNullOrEmpty($minimum) -and
        [string]::IsNullOrEmpty($maximum)) {
        return $Domain.kind
    }
    return "$($Domain.kind):$minimum`:$maximum"
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# Prism filter reference')
$lines.Add('')
$lines.Add('<!-- auto-generated by Tools/scripts/New-PrismFilterReference.ps1; do not edit -->')
$lines.Add("<!-- catalog-sha256: $catalogHash -->")
$lines.Add('')
$lines.Add(
    "Catalog version ``$($catalog.catalogVersion)``. " +
    "$($filters.Count) filters are listed in stable-id order.")
$lines.Add('')
$lines.Add(
    'Conceptual behavior lives in the handwritten Prism filter documents. ' +
    'This file contains only catalog-owned identities, properties, defaults, ' +
    'domains, and execution metadata.')

foreach ($filter in $filters) {
    $profile = $profiles[$filter.category]
    $lines.Add('')
    $lines.Add("## ``$($filter.symbol)`` (``$($filter.id)``)")
    $lines.Add('')
    $lines.Add(
        "- Stable ID: ``$($filter.stableId)``")
    $lines.Add(
        "- Category: ``$($filter.category)``")
    $lines.Add(
        "- Execution: ``$($profile.primitive)``; bounds " +
        "``$($profile.bounds)``; sampling ``$($profile.sampling)``; " +
        "surface ``$($profile.surfaceFormat)``; color space " +
        "``$($profile.colorSpace)``")
    $fusion = if ($null -eq $filter.fusion) {
        'none'
    }
    else {
        $filter.fusion
    }
    $lines.Add(
        "- Deterministic: ``$($filter.deterministic.ToString().ToLowerInvariant())``; " +
        "cacheable: ``$($filter.cacheable.ToString().ToLowerInvariant())``; " +
        "fusion: ``$fusion``")
    $lines.Add('')
    if ($filter.properties.Count -eq 0) {
        $lines.Add('_No filter-specific properties._')
        continue
    }

    $lines.Add('| Property | Type | Required | Default | Domain | Unit |')
    $lines.Add('| --- | --- | ---: | --- | --- | --- |')
    foreach ($property in $filter.properties) {
        $default = if ($property.required) {
            '-'
        }
        else {
            Format-Scalar -Value $property.default
        }
        $domain = Format-Domain -Domain $property.domain
        $required = $property.required.ToString().ToLowerInvariant()
        $lines.Add(
            "| ``$($property.name)`` | ``$($property.valueType)`` | " +
            "``$required`` | ``$default`` | ``$domain`` | " +
            "``$($property.unit)`` |")
    }
}

$parent = [IO.Path]::GetDirectoryName($OutputPath)
[IO.Directory]::CreateDirectory($parent) | Out-Null
$content = [string]::Join([Environment]::NewLine, $lines) +
    [Environment]::NewLine
[IO.File]::WriteAllText(
    $OutputPath,
    $content,
    [Text.UTF8Encoding]::new($false))
Write-Output "Wrote $OutputPath"
