using System;
using System.Text;

namespace Cerneala.SourceGen.Prism;

internal static class PrismOperationSourceEmitter
{
    public static string Emit(PrismCatalogModel model)
    {
        if (model is null)
        {
            throw new ArgumentNullException(nameof(model));
        }

        StringBuilder source = new();
        source.AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("namespace Cerneala.Drawing.Prism;")
            .AppendLine();

        foreach (PrismCatalogCompiler.CatalogEntry entry in model.Entries)
        {
            if (entry.Kind != "filter" && entry.Kind != "style")
            {
                continue;
            }

            bool filter = entry.Kind == "filter";
            string suffix = filter ? "Filter" : "Style";
            string baseType = filter ? "PrismFilter" : "PrismStyle";
            string idType = filter ? "PrismFilterId" : "PrismStyleId";
            source.Append("public sealed class ")
                .Append(entry.Symbol)
                .Append(suffix)
                .Append(" : ")
                .Append(baseType)
                .AppendLine()
                .AppendLine("{")
                .Append("    public ")
                .Append(entry.Symbol)
                .Append(suffix)
                .Append("() : base(global::Cerneala.Drawing.Prism.Catalog.")
                .Append(idType)
                .Append('.')
                .Append(entry.Symbol)
                .AppendLine(")")
                .AppendLine("    {")
                .AppendLine("    }");

            string concreteType = entry.Symbol + suffix;
            AppendMotionProperty(
                source,
                concreteType,
                "Visible",
                "bool",
                isDiscrete: true);
            if (filter)
            {
                AppendMotionProperty(
                    source,
                    concreteType,
                    "Opacity",
                    "float",
                    isDiscrete: false);
                AppendMotionProperty(
                    source,
                    concreteType,
                    "BlendMode",
                    "global::Cerneala.Drawing.Prism.Catalog.PrismBlendMode",
                    isDiscrete: true);
            }

            foreach (PrismCatalogCompiler.CatalogProperty property in entry.Properties)
            {
                string type = PropertyType(property.ValueType);
                AppendMotionProperty(
                    source,
                    concreteType,
                    property.Name,
                    type,
                    IsDiscrete(property.ValueType));
                source.AppendLine()
                    .Append("    public ")
                    .Append(type)
                    .Append(' ')
                    .Append(property.Name)
                    .AppendLine()
                    .AppendLine("    {")
                    .Append("        get => GetParameter<")
                    .Append(type)
                    .Append(">(")
                    .Append(Quote(property.Name))
                    .AppendLine(");")
                    .Append("        set => SetParameter(")
                    .Append(Quote(property.Name))
                    .AppendLine(", value);")
                    .AppendLine("    }");
            }

            source.AppendLine("}")
                .AppendLine();
        }

        return source.ToString();
    }

    private static void AppendMotionProperty(
        StringBuilder source,
        string targetType,
        string propertyName,
        string valueType,
        bool isDiscrete)
    {
        source.AppendLine()
            .Append("    public static readonly global::Cerneala.UI.Motion.MotionProperty<")
            .Append(targetType)
            .Append(", ")
            .Append(valueType)
            .Append("> ")
            .Append(propertyName)
            .AppendLine("Property =")
            .Append("        global::Cerneala.UI.Motion.MotionProperty.")
            .Append(isDiscrete ? "CreateDiscrete" : "Create")
            .Append('<')
            .Append(targetType)
            .Append(", ")
            .Append(valueType)
            .AppendLine(">(")
            .Append("            nameof(")
            .Append(propertyName)
            .AppendLine("),")
            .Append("            static target => target.")
            .Append(propertyName)
            .AppendLine(",")
            .Append("            static (target, value) => target.")
            .Append(propertyName)
            .AppendLine(" = value);");
    }

    private static bool IsDiscrete(string valueType)
    {
        return valueType == "boolean" ||
            valueType == "integer" ||
            valueType == "symbol" ||
            valueType == "resource";
    }

    private static string PropertyType(string valueType)
    {
        switch (valueType)
        {
            case "boolean":
                return "bool";
            case "integer":
                return "int";
            case "number":
                return "float";
            case "color":
                return "global::Cerneala.Drawing.Color";
            case "vector":
                return "global::System.Numerics.Vector4";
            case "symbol":
                return "string";
            case "resource":
                return "global::Cerneala.UI.Prism.Definitions.PrismResourceId";
            default:
                throw new InvalidOperationException(
                    "Unknown Prism parameter value type '" + valueType + "'.");
        }
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
