using System;
using System.Text;

namespace Cerneala.SourceGen.Prism;

internal static class PrismOperationSourceEmitter
{
    public static string Emit(PrismCatalogModel model)
    {
        if (model is null)
        {
            throw new ArgumentNullException(nameof(model));
        }

        StringBuilder source = new();
        source.AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("namespace Cerneala.Drawing.Prism;")
            .AppendLine();

        foreach (PrismCatalogCompiler.CatalogEntry entry in model.Entries)
        {
            if (entry.Kind != "filter" && entry.Kind != "style")
            {
                continue;
            }

            bool filter = entry.Kind == "filter";
            string suffix = filter ? "Filter" : "Style";
            string baseType = filter ? "PrismFilter" : "PrismStyle";
            string idType = filter ? "PrismFilterId" : "PrismStyleId";
            source.Append("public sealed class ")
                .Append(entry.Symbol)
                .Append(suffix)
                .Append(" : ")
                .Append(baseType)
                .AppendLine()
                .AppendLine("{")
                .Append("    public ")
                .Append(entry.Symbol)
                .Append(suffix)
                .Append("() : base(global::Cerneala.Drawing.Prism.Catalog.")
                .Append(idType)
                .Append('.')
                .Append(entry.Symbol)
                .AppendLine(")")
                .AppendLine("    {")
                .AppendLine("    }");

            foreach (PrismCatalogCompiler.CatalogProperty property in entry.Properties)
            {
                string type = PropertyType(property.ValueType);
                source.AppendLine()
                    .Append("    public ")
                    .Append(type)
                    .Append(' ')
                    .Append(property.Name)
                    .AppendLine()
                    .AppendLine("    {")
                    .Append("        get => GetParameter<")
                    .Append(type)
                    .Append(">(")
                    .Append(Quote(property.Name))
                    .AppendLine(");")
                    .Append("        set => SetParameter(")
                    .Append(Quote(property.Name))
                    .AppendLine(", value);")
                    .AppendLine("    }");
            }

            source.AppendLine("}")
                .AppendLine();
        }

        return source.ToString();
    }

    private static string PropertyType(string valueType)
    {
        switch (valueType)
        {
            case "boolean":
                return "bool";
            case "integer":
                return "int";
            case "number":
                return "float";
            case "color":
                return "global::Cerneala.Drawing.Color";
            case "vector":
                return "global::System.Numerics.Vector4";
            case "symbol":
                return "string";
            case "resource":
                return "global::Cerneala.UI.Prism.Definitions.PrismResourceId";
            default:
                throw new InvalidOperationException(
                    "Unknown Prism parameter value type '" + valueType + "'.");
        }
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
