namespace Cerneala.Drawing;

public enum DrawCommandKind
{
    FillRectangle,
    DrawRectangle,
    FillRoundedRectangle,
    DrawRoundedRectangle,
    FillEllipse,
    DrawEllipse,
    DrawLine,
    FillPath,
    DrawText,
    DrawImage,
    DrawImageQuad,
    DrawNineSlice,
    DrawMesh,
    DrawPointBatch,
    DrawLineBatch,
    DrawSpriteBatch,
    RenderSurface2D,
    PushClip,
    PopClip,
    BeginPrism,
    EndPrism,
    DrawPath,
    DrawTextLayout,
    PushTransform,
    PopTransform,
    PushPathClip,
    PushOpacity,
    PopOpacity,
    PushBlend,
    PopBlend,
    PushLayer,
    PopLayer
}
