<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AssemblyName>Cerneala.VisualStudio.IntegrationHost</AssemblyName>
    <RootNamespace>Cerneala.VisualStudio.IntegrationHost</RootNamespace>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <CreateVsixContainer>true</CreateVsixContainer>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeCopyLocalReferencesInVSIXContainer>false</IncludeCopyLocalReferencesInVSIXContainer>
    <DeployExtension>false</DeployExtension>
    <VSSDKTargetPlatformRegRootSuffix>Stage4</VSSDKTargetPlatformRegRootSuffix>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Design" />
    <PackageReference Include="Microsoft.VisualStudio.Editor" Version="17.14.249" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VisualStudio.Language.Intellisense" Version="17.14.249" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VisualStudio.Shell.15.0" Version="17.14.40264" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VisualStudio.Text.UI" Version="17.14.249" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VisualStudio.Text.UI.Wpf" Version="17.14.249" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.9.820" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="source.extension.vsixmanifest" />
    <VSCTCompile Include="Stage4Commands.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>

</Project>
