using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cerneala.SourceGen;

public sealed partial class UiMarkupGenerator
{
    private static void GenerateSceneComponentFile(
        SourceProductionContext context,
        MarkupSource file,
        string className,
        Compilation compilation,
        MarkupComponentPair pair,
        GenerationScope.ApplicationResourceCatalog? applicationResources,
        SourceGeneratorSemanticModel semanticModel)
    {
        if (file.Text is null || !TryGetEmissionDocument(context, file, semanticModel, out EmissionMarkupDocument document))
        {
            return;
        }

        if (document.Root.Attribute("Name") is MarkupAttribute rootName)
        {
            ReportMarkupComponentDiagnostic(context, file,
                "The <Scene2D> root represents this and cannot declare Name.", rootName);
            return;
        }

        MarkupAttribute? nestedDataType = document.Root.Descendants()
            .Where(element => element.Name.LocalName != "ContentTemplate")
            .Select(element => element.Attribute("DataType"))
            .FirstOrDefault(attribute => attribute is not null);
        if (nestedDataType is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidBindingSource,
                CreateLocation(file, nestedDataType), nestedDataType.Value,
                "DataType is allowed only on the root UI element."));
            return;
        }

        INamedTypeSymbol? dataType = ResolveDataType(context, file, document, compilation);
        if (document.Root.Attribute("DataType") is not null && dataType is null)
        {
            return;
        }

        GenerationScope scope = new(context, file, document, compilation, dataType, semanticModel, pair, applicationResources);
        if (scope.HasErrors)
        {
            return;
        }

        scope.EmitElement(document.Root, initializeComponentRoot: true);
        if (scope.HasErrors)
        {
            return;
        }

        StringBuilder source = new();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (!pair.TypeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ").Append(pair.TypeSymbol.ContainingNamespace.ToDisplayString()).AppendLine(";");
            source.AppendLine();
        }

        source.Append("partial class ").Append(pair.TypeSymbol.Name).AppendLine();
        source.AppendLine("{");
        foreach (string line in scope.PrismDeclarationLines)
        {
            source.Append("    ").AppendLine(line);
        }

        source.Append("    public ").Append(pair.TypeSymbol.Name).AppendLine("()");
        source.AppendLine("    {");
        foreach (string line in scope.Lines)
        {
            source.Append("        ").AppendLine(line);
        }

        foreach (string line in scope.PostLines)
        {
            source.Append("        ").AppendLine(line);
        }

        source.AppendLine("    }");
        AppendNamedElementMembers(source, scope.NamedElementMembers);
        source.AppendLine("}");
        string hintName = CreateHintName(file.Path, className).Replace("Factory.", "SceneComponent.");
        context.AddSource(hintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
