using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cerneala.SourceGen;

[Generator]
public sealed class UiMarkupGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MalformedMarkup = new(
        "CERNEALAUI001",
        "Malformed UI markup",
        "Markup file '{0}' could not be parsed: {1}",
        "Cerneala.UiMarkup",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor UnsupportedElement = new(
        "CERNEALAUI002",
        "Unsupported UI markup element",
        "Markup element '{0}' is not supported by the source generator",
        "Cerneala.UiMarkup",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor UnsupportedProperty = new(
        "CERNEALAUI003",
        "Unsupported UI markup property",
        "Markup property '{0}.{1}' is not supported by the source generator",
        "Cerneala.UiMarkup",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidPropertyValue = new(
        "CERNEALAUI004",
        "Invalid UI markup property value",
        "Markup property '{0}.{1}' has invalid value '{2}'",
        "Cerneala.UiMarkup",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<MarkupSource> markupFiles = context.AdditionalTextsProvider
            .Where(static file => IsMarkupFile(file))
            .Select(static (file, cancellationToken) => new MarkupSource(
                file.Path,
                file.GetText(cancellationToken)?.ToString()));

        context.RegisterSourceOutput(markupFiles.Collect(), static (sourceContext, files) => GenerateFiles(sourceContext, files));
    }

    private static bool IsMarkupFile(AdditionalText file)
    {
        return file.Path.EndsWith(".cui.xml", StringComparison.OrdinalIgnoreCase);
    }

    private static void GenerateFiles(SourceProductionContext context, ImmutableArray<MarkupSource> files)
    {
        string[] classNames = AssignClassNames(files);
        for (int i = 0; i < files.Length; i++)
        {
            GenerateFile(context, files[i], classNames[i]);
        }
    }

    private static string[] AssignClassNames(ImmutableArray<MarkupSource> files)
    {
        string[] classNames = files.Select(file => CreateClassName(file.Path)).ToArray();
        foreach (var group in classNames.Select((name, index) => new { name, index }).GroupBy(item => item.name, StringComparer.Ordinal))
        {
            if (group.Count() == 1)
            {
                continue;
            }

            foreach (int index in group.Select(item => item.index))
            {
                classNames[index] = CreateDisambiguatedClassName(files[index].Path);
            }
        }

        foreach (var group in classNames.Select((name, index) => new { name, index }).GroupBy(item => item.name, StringComparer.Ordinal))
        {
            if (group.Count() == 1)
            {
                continue;
            }

            foreach (int index in group.Select(item => item.index))
            {
                classNames[index] = classNames[index] + "_" + Fnv1a32(files[index].Path.Replace('\\', '/').ToUpperInvariant()).ToString("x8", CultureInfo.InvariantCulture);
            }
        }

        return classNames;
    }

    private static void GenerateFile(SourceProductionContext context, MarkupSource file, string className)
    {
        if (file.Text is null)
        {
            return;
        }

        XDocument document;
        try
        {
            document = XDocument.Parse(file.Text, LoadOptions.SetLineInfo | LoadOptions.PreserveWhitespace);
        }
        catch (XmlException ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(MalformedMarkup, CreateLocation(file, ex.LineNumber, ex.LinePosition), Path.GetFileName(file.Path), ex.Message));
            return;
        }

        if (document.Root is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(MalformedMarkup, CreateLocation(file, 1, 1), Path.GetFileName(file.Path), "Root element is missing."));
            return;
        }

        GenerationScope scope = new(context, file);
        string rootVariable = scope.EmitElement(document.Root);
        if (scope.HasErrors)
        {
            return;
        }

        StringBuilder source = new();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Cerneala.GeneratedUi;");
        source.AppendLine();
        source.Append("public static partial class ").Append(className).AppendLine("Factory");
        source.AppendLine("{");
        source.AppendLine("    public static global::Cerneala.UI.Elements.UIElement Create()");
        source.AppendLine("    {");
        foreach (string line in scope.Lines)
        {
            source.Append("        ").AppendLine(line);
        }

        source.Append("        return ").Append(rootVariable).AppendLine(";");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static global::Cerneala.UI.Markup.GeneratedUiFactory AsGeneratedFactory()");
        source.AppendLine("    {");
        source.AppendLine("        return new global::Cerneala.UI.Markup.GeneratedUiFactory(Create);");
        source.AppendLine("    }");
        source.AppendLine("}");

        string hintName = CreateHintName(file.Path, className);
        context.AddSource(hintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string CreateClassName(string path)
    {
        string rawName = Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(path));
        return CreateIdentifier(rawName);
    }

    private static string CreateDisambiguatedClassName(string path)
    {
        string? directoryName = Path.GetDirectoryName(path);
        string? parentName = string.IsNullOrEmpty(directoryName) ? null : Path.GetFileName(directoryName);
        string baseName = Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(path));
        return string.IsNullOrEmpty(parentName)
            ? CreateClassName(path)
            : CreateIdentifier(parentName + "-" + baseName);
    }

    private static string CreateHintName(string path, string className)
    {
        string stableSuffix = Fnv1a32(path.Replace('\\', '/').ToUpperInvariant()).ToString("x8", CultureInfo.InvariantCulture);
        return className + "Factory." + stableSuffix + ".g.cs";
    }

    private static string CreateIdentifier(string rawName)
    {
        StringBuilder builder = new();
        bool capitalizeNext = true;
        foreach (char character in rawName)
        {
            if (!char.IsLetterOrDigit(character) && character != '_')
            {
                capitalizeNext = true;
                continue;
            }

            char value = builder.Length == 0 && char.IsDigit(character) ? '_' : character;
            builder.Append(capitalizeNext ? char.ToUpperInvariant(value) : value);
            capitalizeNext = false;
        }

        return builder.Length == 0 ? "GeneratedUi" : builder.ToString();
    }

    private static uint Fnv1a32(string value)
    {
        const uint offset = 2166136261;
        const uint prime = 16777619;
        uint hash = offset;
        foreach (char character in value)
        {
            hash ^= character;
            hash *= prime;
        }

        return hash;
    }

    private readonly struct MarkupSource
    {
        public MarkupSource(string path, string? text)
        {
            Path = path;
            Text = text;
        }

        public string Path { get; }

        public string? Text { get; }
    }

    private sealed class GenerationScope
    {
        private readonly SourceProductionContext context;
        private readonly MarkupSource file;
        private int nextId;

        public GenerationScope(SourceProductionContext context, MarkupSource file)
        {
            this.context = context;
            this.file = file;
        }

        public List<string> Lines { get; } = new();

        public bool HasErrors { get; private set; }

        public string EmitElement(XElement element)
        {
            string variable = "element" + nextId.ToString(CultureInfo.InvariantCulture);
            nextId++;

            string? typeName = element.Name.LocalName switch
            {
                "Panel" => "global::Cerneala.UI.Controls.Panel",
                "StackPanel" => "global::Cerneala.UI.Controls.StackPanel",
                "Border" => "global::Cerneala.UI.Controls.Border",
                "Button" => "global::Cerneala.UI.Controls.Button",
                "TextBlock" => "global::Cerneala.UI.Controls.TextBlock",
                _ => null
            };

            if (typeName is null)
            {
                Report(UnsupportedElement, element, element.Name.LocalName);
                return variable;
            }

            Lines.Add(typeName + " " + variable + " = new();");
            foreach (XAttribute attribute in element.Attributes().Where(attribute => !attribute.IsNamespaceDeclaration))
            {
                EmitProperty(element, variable, attribute);
            }

            string? directText = ReadDirectText(element);
            if (directText is not null)
            {
                EmitTextContent(element, variable, directText);
            }

            foreach (XElement child in element.Elements())
            {
                string childVariable = EmitElement(child);
                EmitChild(element, variable, childVariable);
            }

            return variable;
        }

        private void EmitProperty(XElement element, string variable, XAttribute attribute)
        {
            string elementName = element.Name.LocalName;
            string propertyName = attribute.Name.LocalName;
            string value = attribute.Value;

            string? expression = propertyName switch
            {
                "Text" when elementName == "TextBlock" => Literal(value),
                "Content" when elementName == "Button" => Literal(value),
                "IsEnabled" => Bool(attribute),
                "IsVisible" => Bool(attribute),
                "Margin" => Thickness(elementName, propertyName, attribute),
                "Background" when IsControlElement(elementName) => Color(elementName, propertyName, attribute),
                "Foreground" when IsControlElement(elementName) => Color(elementName, propertyName, attribute),
                "BorderColor" when IsControlElement(elementName) => Color(elementName, propertyName, attribute),
                "BorderThickness" when IsControlElement(elementName) => NonNegativeThickness(elementName, propertyName, attribute),
                "Padding" when IsControlElement(elementName) => NonNegativeThickness(elementName, propertyName, attribute),
                "FontFamily" when IsControlElement(elementName) && !string.IsNullOrWhiteSpace(value) => Literal(value),
                "FontSize" when IsControlElement(elementName) => PositiveFloat(elementName, propertyName, attribute),
                _ => null
            };

            if (expression is null)
            {
                if (!HasErrors)
                {
                    Report(UnsupportedProperty, attribute, elementName, propertyName);
                }

                return;
            }

            Lines.Add(variable + "." + propertyName + " = " + expression + ";");
        }

        private void EmitTextContent(XElement element, string variable, string text)
        {
            switch (element.Name.LocalName)
            {
                case "TextBlock":
                    Lines.Add(variable + ".Text = " + Literal(text) + ";");
                    break;
                case "Button":
                    Lines.Add(variable + ".Content = " + Literal(text) + ";");
                    break;
                default:
                    Report(UnsupportedProperty, element, element.Name.LocalName, "#text");
                    break;
            }
        }

        private void EmitChild(XElement parent, string parentVariable, string childVariable)
        {
            switch (parent.Name.LocalName)
            {
                case "Panel":
                case "StackPanel":
                    Lines.Add(parentVariable + ".LogicalChildren.Add(" + childVariable + ");");
                    Lines.Add(parentVariable + ".VisualChildren.Add(" + childVariable + ");");
                    break;
                case "Border":
                    Lines.Add(parentVariable + ".Child = " + childVariable + ";");
                    break;
                case "Button":
                    Lines.Add(parentVariable + ".Content = " + childVariable + ";");
                    break;
                default:
                    Report(UnsupportedProperty, parent, parent.Name.LocalName, "#child");
                    break;
            }
        }

        private static string? ReadDirectText(XElement element)
        {
            string text = string.Concat(element.Nodes().OfType<XText>().Select(node => node.Value));
            return string.IsNullOrWhiteSpace(text) ? null : text.Trim();
        }

        private static bool IsControlElement(string elementName)
        {
            return elementName is "Border" or "Button" or "TextBlock";
        }

        private static string Literal(string value)
        {
            StringBuilder builder = new();
            builder.Append('"');
            foreach (char character in value)
            {
                builder.Append(character switch
                {
                    '\\' => "\\\\",
                    '"' => "\\\"",
                    '\0' => "\\0",
                    '\a' => "\\a",
                    '\b' => "\\b",
                    '\f' => "\\f",
                    '\n' => "\\n",
                    '\r' => "\\r",
                    '\t' => "\\t",
                    '\v' => "\\v",
                    _ when char.IsControl(character) => "\\u" + ((int)character).ToString("x4", CultureInfo.InvariantCulture),
                    _ => character.ToString()
                });
            }

            builder.Append('"');
            return builder.ToString();
        }

        private string? Bool(XAttribute attribute)
        {
            return bool.TryParse(attribute.Value, out bool parsed) ? (parsed ? "true" : "false") : Invalid(attribute, "Boolean", "value", attribute.Value);
        }

        private string? Float(string elementName, string propertyName, XAttribute attribute)
        {
            string value = attribute.Value;
            return float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed) &&
                !float.IsNaN(parsed) &&
                !float.IsInfinity(parsed)
                ? parsed.ToString("R", CultureInfo.InvariantCulture) + "f"
                : Invalid(attribute, elementName, propertyName, value);
        }

        private string? PositiveFloat(string elementName, string propertyName, XAttribute attribute)
        {
            string value = attribute.Value;
            return float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed) &&
                parsed > 0 &&
                !float.IsNaN(parsed) &&
                !float.IsInfinity(parsed)
                ? parsed.ToString("R", CultureInfo.InvariantCulture) + "f"
                : Invalid(attribute, elementName, propertyName, value);
        }

        private string? Thickness(string elementName, string propertyName, XAttribute attribute)
        {
            string value = attribute.Value;
            string[] parts = value.Split(',').Select(part => part.Trim()).ToArray();
            if (parts.Length == 1 && FloatPart(elementName, propertyName, attribute, parts[0]) is string uniform)
            {
                return "new global::Cerneala.UI.Layout.Thickness(" + uniform + ")";
            }

            if (parts.Length == 1)
            {
                return null;
            }

            if (parts.Length == 4)
            {
                string? left = FloatPart(elementName, propertyName, attribute, parts[0]);
                string? top = FloatPart(elementName, propertyName, attribute, parts[1]);
                string? right = FloatPart(elementName, propertyName, attribute, parts[2]);
                string? bottom = FloatPart(elementName, propertyName, attribute, parts[3]);
                if (left is not null && top is not null && right is not null && bottom is not null)
                {
                    return "new global::Cerneala.UI.Layout.Thickness(" + left + ", " + top + ", " + right + ", " + bottom + ")";
                }

                return null;
            }

            return Invalid(attribute, elementName, propertyName, value);
        }

        private string? NonNegativeThickness(string elementName, string propertyName, XAttribute attribute)
        {
            string value = attribute.Value;
            string[] parts = value.Split(',').Select(part => part.Trim()).ToArray();
            if (parts.Length == 1 && NonNegativeFloatPart(elementName, propertyName, attribute, parts[0]) is string uniform)
            {
                return "new global::Cerneala.UI.Layout.Thickness(" + uniform + ")";
            }

            if (parts.Length == 1)
            {
                return null;
            }

            if (parts.Length == 4)
            {
                string? left = NonNegativeFloatPart(elementName, propertyName, attribute, parts[0]);
                string? top = NonNegativeFloatPart(elementName, propertyName, attribute, parts[1]);
                string? right = NonNegativeFloatPart(elementName, propertyName, attribute, parts[2]);
                string? bottom = NonNegativeFloatPart(elementName, propertyName, attribute, parts[3]);
                if (left is not null && top is not null && right is not null && bottom is not null)
                {
                    return "new global::Cerneala.UI.Layout.Thickness(" + left + ", " + top + ", " + right + ", " + bottom + ")";
                }

                return null;
            }

            return Invalid(attribute, elementName, propertyName, value);
        }

        private string? FloatPart(string elementName, string propertyName, XAttribute attribute, string value)
        {
            return float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed) &&
                !float.IsNaN(parsed) &&
                !float.IsInfinity(parsed)
                ? parsed.ToString("R", CultureInfo.InvariantCulture) + "f"
                : Invalid(attribute, elementName, propertyName, attribute.Value);
        }

        private string? NonNegativeFloatPart(string elementName, string propertyName, XAttribute attribute, string value)
        {
            return float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out float parsed) &&
                parsed >= 0 &&
                !float.IsNaN(parsed) &&
                !float.IsInfinity(parsed)
                ? parsed.ToString("R", CultureInfo.InvariantCulture) + "f"
                : Invalid(attribute, elementName, propertyName, attribute.Value);
        }

        private string? Color(string elementName, string propertyName, XAttribute attribute)
        {
            string value = attribute.Value;
            if (string.Equals(value, "Transparent", StringComparison.OrdinalIgnoreCase))
            {
                return "global::Cerneala.Drawing.DrawColor.Transparent";
            }

            if (string.Equals(value, "White", StringComparison.OrdinalIgnoreCase))
            {
                return "global::Cerneala.Drawing.DrawColor.White";
            }

            if (string.Equals(value, "Black", StringComparison.OrdinalIgnoreCase))
            {
                return "global::Cerneala.Drawing.DrawColor.Black";
            }

            string[] parts = value.Split(',').Select(part => part.Trim()).ToArray();
            if (parts.Length is 3 or 4 &&
                byte.TryParse(parts[0], NumberStyles.Integer, CultureInfo.InvariantCulture, out byte r) &&
                byte.TryParse(parts[1], NumberStyles.Integer, CultureInfo.InvariantCulture, out byte g) &&
                byte.TryParse(parts[2], NumberStyles.Integer, CultureInfo.InvariantCulture, out byte b) &&
                (parts.Length == 3 || byte.TryParse(parts[3], NumberStyles.Integer, CultureInfo.InvariantCulture, out _)))
            {
                string alpha = parts.Length == 4 ? ", " + parts[3] : string.Empty;
                return "new global::Cerneala.Drawing.DrawColor(" + r + ", " + g + ", " + b + alpha + ")";
            }

            return Invalid(attribute, elementName, propertyName, value);
        }

        private string? Invalid(XAttribute attribute, string elementName, string propertyName, string value)
        {
            Report(InvalidPropertyValue, attribute, elementName, propertyName, value);
            return null;
        }

        private void Report(DiagnosticDescriptor descriptor, object locationSource, params object[] args)
        {
            HasErrors = true;
            context.ReportDiagnostic(Diagnostic.Create(descriptor, CreateLocation(file, locationSource), args));
        }
    }

    private static Location CreateLocation(MarkupSource file, object locationSource)
    {
        if (locationSource is XObject xmlObject)
        {
            return CreateLocation(file, xmlObject);
        }

        return Location.Create(file.Path, TextSpan.FromBounds(0, 0), new LinePositionSpan(new LinePosition(0, 0), new LinePosition(0, 0)));
    }

    private static Location CreateLocation(MarkupSource file, XObject xmlObject)
    {
        if (xmlObject is IXmlLineInfo lineInfo && lineInfo.HasLineInfo())
        {
            return CreateLocation(file, lineInfo.LineNumber, lineInfo.LinePosition);
        }

        return CreateLocation(file, 1, 1);
    }

    private static Location CreateLocation(MarkupSource file, int oneBasedLine, int oneBasedColumn)
    {
        SourceText sourceText = SourceText.From(file.Text ?? string.Empty, Encoding.UTF8);
        int line = Math.Max(0, Math.Min(sourceText.Lines.Count - 1, oneBasedLine - 1));
        int column = Math.Max(0, oneBasedColumn - 1);
        int start = Math.Min(sourceText.Length, sourceText.Lines[line].Start + column);
        LinePosition position = sourceText.Lines.GetLinePosition(start);
        return Location.Create(file.Path, TextSpan.FromBounds(start, start), new LinePositionSpan(position, position));
    }
}
